export const ERROR_CODES = {
  // Auth & Roles
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN_ROLE: 'AUTH_FORBIDDEN_ROLE',

  // Domain Entity Errors
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  BRANCH_NOT_FOUND: 'BRANCH_NOT_FOUND',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',

  // Stock & Inventory
  INVENTORY_INSUFFICIENT_STOCK: 'INVENTORY_INSUFFICIENT_STOCK',
  INVENTORY_BRANCH_MISMATCH: 'INVENTORY_BRANCH_MISMATCH',
  TRANSFER_INVALID_STATUS: 'TRANSFER_INVALID_STATUS',

  // System & Database
  DATABASE_DUPLICATE_KEY: 'DATABASE_DUPLICATE_KEY',
  DATABASE_FOREIGN_KEY_VIOLATION: 'DATABASE_FOREIGN_KEY_VIOLATION',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;
